### ISSUE TITLE
Expected behaviors of failed verification

### ISSUE THREAD

**Issue by junxzm1990** [DelphinusLab/zkWasm#136]
Are there any instructions regarding determining failed verifications? I suppose that "halo2_proofs::plonk::verify_proof" should return "false", right?  

I am running into a case where "single-verify" panicked due to [`Result::unwrap()` on an `Err` value: ConstraintSystemFailure', src/cli/exec.rs:354:6]. Does this indicate a failed verification or something else?

**Comment by junyu0312** [comment]
Yes, `ConstraintSystemFailure` indicates a failure verification.
