### ISSUE TITLE
Unknown opcode 192

### ISSUE THREAD

**Issue by LichuAcu** [DelphinusLab/zkWasm#145]
When trying to run `single-prove` on the Rust program compiled to WASM found in the [sample Rust repo](https://github.com/xgaozoyoe/zkWasm-Rust-Demo), I get this error:
```
thread 'main' panicked at 'failed to load wasm: Validation("Unknown opcode 192")', 
./zkWasm/src/cli/app_builder.rs:77:67
```

I see in the internet that this may have something to do with using the nightly-2022-11-23 toolchain, but when changed some experimental Rust features stop working.

Would really appreciate some help. Thank you!

**Comment by junyu0312** [comment]
Try to use `wasm-opt` with `--signext-lowering` flag to eliminate the unsupported opcode, for example

`wasm-opt -O3 pkg/zkwasm_rlp_bg.wasm -o zkwasm_rlp_bg.wasm --signext-lowering`
