### ISSUE TITLE
`Error: Trap: Code(UnexpectedSignature)` when trying to run `single-prove`

### ISSUE THREAD

**Issue by Mikerah** [DelphinusLab/zkWasm#201]
I have compiled the following code to wasm:
```
extern crate wasm_bindgen;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn zkmain() -> String {
    "Hello, wasm!".to_string()
}
```
I'm able to successfully call `cargo run --release -- --function <FUNCTION_NAME> --wasm <WASM_BINARY> setup` with various choices of k.  However, when I try to run `cargo run --release -- --function <FUNCTION_NAME> --wasm <WASM_BINARY> single-prove` with different choices of k I get the following error:
```
read params K=23 from "B59B97F994C21CDF161C56A568935F53/K23.params"
read vkey from "B59B97F994C21CDF161C56A568935F53/zkwasm.0.vkey.data"
quotient_poly_degree 4
Error: Trap: Code(UnexpectedSignature)
```

I'm not sure what's causing this since in issue #96, the author also has a simple function signature. 
Any hints as to how to fix this?

**Comment by junyu0312** [comment]
Please avoid returning `String` for zkmain. wasm-bindgen emits the `zkmain` with a param that is not supported by `zkWasm`'s entry function.

**Comment by Mikerah** [comment]
What type should I use?

**Comment by xgaozoyoe** [comment]
please move this issue to https://github.com/DelphinusLab/zkWasm-rust which is related to rust SDK for zkwasm
