### ISSUE TITLE
got "Error: Validation: Unknown opcode 252"  when setup wasm from assemblyscript

### ISSUE THREAD

**Issue by lightszero** [DelphinusLab/zkWasm#235]
I write a AssemblyScript  code like:

```typescript
@external("env", "wasm_input")
declare function wasm_input(x: i32): i64


@external("env", "require")
declare function require(x: i32): void

export function zkmain(): void {
    //一次性读出n个数据不过分吧。
    var arra: i64[] = [];
    let count = wasm_input(0);
    for (var i = 0; i < count; i++) {
        let v = wasm_input(0);
        arra.push(v);
    }
    var datab = wasm_input(1);
    require(arra[0] == datab);
}
```

and got a error when setup:
Error: Validation: Unknown opcode 252

**Comment by akayi07** [comment]
> I write a AssemblyScript code like:
> 
> ```ts
> @external("env", "wasm_input")
> declare function wasm_input(x: i32): i64
> 
> 
> @external("env", "require")
> declare function require(x: i32): void
> 
> export function zkmain(): void {
>     //一次性读出n个数据不过分吧。
>     var arra: i64[] = [];
>     let count = wasm_input(0);
>     for (var i = 0; i < count; i++) {
>         let v = wasm_input(0);
>         arra.push(v);
>     }
>     var datab = wasm_input(1);
>     require(arra[0] == datab);
> }
> ```
> 
> and got a error when setup: Error: Validation: Unknown opcode 252

Run  command such as `asc zk.ts -O --noAssert -o ../zk_testc1.wasm --disable bulk-memory  --runtime stub --use abort=zk/abort`.

**Comment by xgaozoyoe** [comment]
Closed as solved.
