### ISSUE TITLE
chore: issue format spec

### ISSUE THREAD

**Issue by aseaday** [DelphinusLab/zkWasm#29]
Hi, I want to contributed to the awesome zkwasm project. But there is some difficutly for me to do so. The issue need some labels and format for others to know more details. Here is a example:
```markdown
## Description

---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

```
I could help you to build label system/bot and issue format to help more guys know the flow of contributing

**Comment by aseaday** [comment]
Here is the issues labels system specs:
chore: non-feature requirements such as CI/CD, building script or work flow enhancement.
feat: feature need, we could use feat(circuit), feat(lang), feat(CLI) to categorize features
bug: bug report, we also could use bug(circuit), bug(lang) to categorize bugs
doc: documents related issues.

**Comment by xgaozoyoe** [comment]
nice point! We will follow.
