### ISSUE TITLE
feat: add support or workaround for bulk-memory-operations

### ISSUE THREAD

**Issue by aseaday** [DelphinusLab/zkWasm#54]
## Description
We now need to support compiled wasm from assembly script. 
The assembly script use [bulk-memory-operations](https://github.com/WebAssembly/bulk-memory-operations/blob/master/proposals/bulk-memory-operations/Overview.md) to implement `array` in typescript. The Opcode are in `0xfc` or `252`.

```typescript
export function test_array(): Array<i32> {
  return [42]
}
```
which will generate wasm code:

```webassembly
 (func $~lib/rt/__newBuffer (param $0 i32) (param $1 i32) (param $2 i32) (result i32)
  (local $3 i32)
  local.get $0
  local.get $1
  call $~lib/rt/itcms/__new
  local.set $3
  local.get $2
  if
   local.get $3
   local.get $2
   local.get $0
   memory.copy $0 $0 ;; This is what we lacked now!
  end
  local.get $3
 )
```
We use [wasmi](https://github.com/paritytech/wasmi) and it didn't support bulk-memory-operations. When wasmi run this script, it will throw:

```
read file from /Users/nullday/Workplace/zkWasm/asctest/array.wasm
thread 'main' panicked at 'failed to load wasm: Validation("Unknown opcode 252")', src/runtime/wasmi_interpreter.rs:51:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

we have two ways to solve this problem:

- add support for bulk-memory-operations on our fork wasmi
- make asc(assembly script compiler) not use bulk-memory-operations/ to implement array which most probably means that we modify the lib/rt/__newBuffer 
- ask users to use `npx asc array.ts --disable bulk-memory -o array.wasm` to disable bulk-memory features.

## Goal

Pass https://github.com/DelphinusLab/zkWasm/pull/55

**Comment by lanbones** [comment]
We won't support bulk-memory-operations in short-term because our framework only supports instructions that involves limited memory access. But I would like to put it into plan. Let's first ask user to use `--disable bulk-memory` once we have document.

**Comment by xgaozoyoe** [comment]
Let's close this since a PR for bulk memory support is ready (see https://github.com/DelphinusLab/zkWasm/pull/86)
