### ISSUE TITLE
Simple programs crash with "not yet implemented"

### ISSUE THREAD

**Issue by naps62** [DelphinusLab/zkWasm#70]
A lot of simple examples seem to fail to run due to `todo!()` tags. From a quick look, this seems to be on `wasmi` itself, not your repo. Essentially lots of instructions still yet to be implemented on that side
As I'm not familiar with wasmi, not sure if there is a timeline to expect full compatibility?

Example:

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn parse() {
    let data = vec![0x83, b'c', b'a', b't'];
    let animal: String = rlp::decode(&data).expect("could not decode");
    assert_eq!(animal, "cat".to_owned());
}
```

fails with:
```
thread 'main' panicked at 'not yet implemented', wasmi/src/isa.rs:589:36
```

When checking `wasmi/src/isa.rs` it can be seen that a lot of instructions are still `todo!()`

**Comment by laoliang2021** [comment]
Would you please be a bit more specific about what non-float instructions you are after? Some may have been tracked.

**Comment by laoliang2021** [comment]
Ok, no problem. I think we do not have a concrete timeline for float point arith at the moment, but we will check Clz and Ctz.

**Comment by junyu0312** [comment]
We have implemented ctz/clz instructions last week. https://github.com/DelphinusLab/zkWasm/pull/71

**Comment by naps62** [comment]
@junyu0312 thanks, but this doesn't seem to fully do it.

Trying the same program (on the original issue) I now run into other unimplemented behaviour:

```
thread 'main' panicked at 'not yet implemented', wasmi/src/isa.rs:504:40
```

which seems to be on the `Instruction::GrowMemory` instruction
