### ISSUE TITLE
Refactor: gather all basic constrains as a gadget

### ISSUE THREAD

**Issue by ChengYueJia** [DelphinusLab/zkWasm#88]
I've seen some dup-constrains in xxx.configure. Like `MemoryTableConfig.configure_enable_as_bit`  and the `JumpTableConfig.enable_is_bit`.

Seems like it's better to gather all basic constrains as a gadget to make the code structure clearer.

The zkevm did a good job. Maybe we can learn from it. 
https://github.com/privacy-scaling-explorations/zkevm-circuits

**Comment by xgaozoyoe** [comment]
It is closed as it is a bit too generic.
