### ISSUE TITLE
Failure to run basic rlp decoding program

### ISSUE THREAD

**Issue by naps62** [DelphinusLab/zkWasm#91]
Tried to run the following code:

```rust
// src/lib.rs
#[wasm_bindgen]
pub fn add() -> i64 {
    let data = vec![0x83, b'c', b'a', b't'];
    let animal: String = rlp::decode(&data).expect("could not decode");
    assert_eq!(animal, "cat".to_owned());

    0
}
```

```Justfile
# justfile
wasm := "pkg/rlp_bg.wasm"
cli := "../../DelphinusLab/zkWasm/target/release/cli"
args := "--function add --output ./output --wasm " + wasm
proof := "output/zkwasm.0.transcript.data"
public_input := "5:i64"

build:
  wasm-pack build --release

# skipped if zkwasm.0.vkey.data is up-to-date
setup: build
  {{cli}} {{args}} setup

# skipped if zkwasm.0.vkey.data is up-to-date
run: setup
  {{cli}} {{args}} single-prove --public {{public_input}}

verify: run
  {{cli}} {{args}} single-verify --public {{public_input}} --proof {{proof}}
```

calling `just run` yieled the following:
![image](https://user-images.githubusercontent.com/283819/211554236-f7649e01-fb56-474a-9849-712d6820d2a7.png)

**Comment by junyu0312** [comment]
We appreciate your feedback. Please

1. update zkwasm, recompile it, and clear up your `output` directory,
2. since your rust code doesn't call `wasm_input` method, remove `--public 5:i64` argument,
3. increase the circuit size to K=19 via a new command argument `-k 19`

For example,

```
./target/release/cli -k 19 --function add --output ./output --wasm rlp_bg.wasm setup
./target/release/cli -k 19 --function add --output ./output --wasm rlp_bg.wasm single-prove
./target/release/cli -k 19 --function add --output ./output --wasm rlp_bg.wasm single-verify --proof output/zkwasm.0.transcript.data
```

**Comment by naps62** [comment]
@junyu0312 seems to work now. thank you!

One follow-up question though: I couldn't find any documentation or example on how to access the output of the execution. Is there such an example?

**Comment by naps62** [comment]
@junyu0312 I'm not sure if I incorrectly tested 2 weeks ago, or if there's some regression, but this is now failing again.

I tried with a few different commits of zkwasm.
also commented the `assert_eq!` part of the program. it still crashes. the problem seems to be on the `rlp::decode` call

I extracted the code into a separate repo for debugging: github.com/naps62/zkwasm-hello-world

**Comment by lanbones** [comment]
Thank you very much to report this issue. It is related to a bug on negative numbers' comparison. The PR  #100 is waiting for @junyu0312 review. You can try zkWasm on commit d375af87fced482c0f99c08ca14b7434a2ce0a09 before merge.
